### ISSUE TITLE
Dockerize It ?!

### ISSUE THREAD

**Issue by sooluh** [stackpan/qurancord#1]
Saya kurang tahu menahu tentang Java, sepertinya perlu banyak dependensi yang saya Install di device saya, ini sangat membantu jika di bungkus dalam kontainer Docker!

**Comment by stackpan** [comment]
Ok, nanti saya buat image secepatnya

**Comment by stackpan** [comment]
Image kami sudah tersedia di [Docker hub](https://hub.docker.com/r/ivanzkyanto/qurancord)!

Silahkan ikuti instruksi di sana atau bisa cek di [Readme kami](https://github.com/stackpan/qurancord#docker-image)

**Comment by sooluh** [comment]
Great work, Thanks!
