### ISSUE TITLE
It would be really cool to apply lafzi here!

### ISSUE THREAD

**Issue by sooluh** [stackpan/qurancord#2]
Barangkali belum mengenal, saya coba kenalkan, lafzi merupakan mesin pencari Al-Qur'an berdasarkan lafadz dengan bahasa indonesia, mungkin lebih lengkapnya boleh kunjungi [halaman organisasinya](https://github.com/lafzi)

Secara resmi, belum ada library untuk java, namun sudah tersedia library untuk PHP (bahasa awal yang digunakan) dan juga javascript dari pengembangannya.

Mungkin antum bisa sekalian mengembangkan library untuk java-nya?

**Comment by stackpan** [comment]
Menarik, terimakasih atas sarannya.

Nanti saya akan mencoba membuat implementasi Java-nya tetapi tidak dalam waktu yang dekat.

Ngomong-ngomong, lafzi yang anda tunjukkan mungkin tidak bisa ditambahkan di project ini. Karena setelah saya melihat-lihat repo indexer nya, lafzi membutuhkan seluruh data Al-Quran terlebih dahulu untuk meng-index pencarian lafadz-nya. Sedangkan cara kerja Qurancord tidak mengambil seluruh data Al-Quran terlebih dahulu, melainkan secara _lazy_ mengambil data per surah sesuai permintaan user.

**Comment by stackpan** [comment]
Mari saya jelaskan cara kerja pengambilan data Al-Quran di Qurancord secara garis besar:
1. Ketika ada request command dari user, qurancord akan mencari data surat (sesuai permintaan request user) terlebih dahulu di memory (ya memory, kami tidak menggunakan in-memory database seperti Redis, Memcaced dan sebagainya karena itu terlalu _overkill_ hanya untuk menyimpan data Al-Quran. Kami cukup memanfaatkan library Java Collection saja)
2. Jika data di memory tidak ada, barulah qurancord akan mengirim request ke API data Al-Quran itu berada ([equran.id](https://equran.id/))
3. Mengikuti spesifikasi endpoint yang tersedia di [equran.id](https://equran.id/apidev). 
   - Untuk data surah, Qurancord akan mengambil semua detail data surah (hanya data detail surah, tidak termasuk ayat-ayatnya), 
   - Sedangkan data ayat, Qurancord akan mengambil semua ayat di surah tersebut.
4. Hasil response tersebut akan diteruskan ke user dan disimpan di memory
5. Jika terdapat request command lagi yang membutuhkan data surah/ayat yang sama, maka qurancord hanya akan mengambilnya dari memory

Tujuan kami membuatnya seperti ini adalah untuk mengurangi banyaknya request ke API.

**Comment by stackpan** [comment]
Seperti ini kalau digambarkan dalam bentuk flowchart:

![Diagram Tanpa Judul drawio](https://user-images.githubusercontent.com/55195033/221601735-ed4f8f19-ca26-4f37-af71-e581e55ba5a6.png)

**Comment by stackpan** [comment]
Dan alasan lain lafzi tidak bisa ditambahkan di project ini, yaitu fitur image generation kami. Jika ditambahkan, kami tidak akan menambahkan _highlighting_ yang terdapat di lafzi. Karena highlighting akan membuat mesin yang menjalankan Qurancord dapat men-generate image ayat dalam jumlah banyak. Asumsikan saja untuk membuat satu image ayat itu membutuhkan resource yang lumayan banyak di JVM, sampai-sampai kami membuat thread (worker) khusus untuk image generator.

![image](https://user-images.githubusercontent.com/55195033/221615131-fee85dba-6686-4c50-a272-9011eb84f2b4.png)
[Replier.java](https://github.com/stackpan/qurancord/blob/main/bot/src/main/java/com/stackpan/qurancord/bot/Replier.java)

**Comment by stackpan** [comment]
Kalau _highlighting_ ditambahkan, bisa saja ayat yang sama akan mempunyai banyak image (prinsip cara kerja image generator kami sama seperti pengambilan data Al-Quran dari api: Ambil image yang sudah ada, jika tidak ada maka generate image baru). Misalkan saja terdapat dua gambar ayat yang sama yang meng-_highlight_ lafadz yang berbeda. Itu baru dua gambar, nah jika terdapat puluhan ratusan bahkan ribuan gambar hanya untuk ayat yang sama! Apalagi jika ayat tersebut panjang, maka akan terdapat banyak kombinasi _highlight_ di ayat tersebut.

Itu akan memakan banyak penyimpanan gambar bagi mesin yang menjalankan Qurancord. (Qurancord menyimpan hasil generate gambar di folder .res dan berada di direktori yang sama dengan file JAR tersebut berada)

**Comment by stackpan** [comment]
Yang saya jelaskan tadi sudah kami rencanakan dari awal sebelum project ini dibuat. Kami bisa saja mengubah cara kerja itu semua, tetapi itu sama saja dengan kami membuat ulang Qurancord.

Sekali lagi, terima kasih. Saya akan mempelajari lafzi lebih lanjut.

**Comment by sooluh** [comment]
Cool answer! Baik saya tutup issue ini :smiley:
